### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by Baka943-0v0** [gfuil/BmapLite#2]
日志如下
java.lang.RuntimeException: Unable to create application me.gfuil.bmap.lite.BApp: java.lang.RuntimeException: please check whether the customMapStylePath file exits
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6022)
	at android.app.ActivityThread.access$1200(ActivityThread.java:202)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.RuntimeException: please check whether the customMapStylePath file exits
	at com.baidu.mapapi.map.MapView.setCustomMapStylePath(Unknown Source:24)
	at me.gfuil.bmap.lite.BApp.initMap(BApp.java:91)
	at me.gfuil.bmap.lite.BApp.onCreate(BApp.java:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6017)
	... 8 more

**Comment by chenlongEX** [comment]
@tartaricacid943 闪退就用32位版本，官网有32位版本下载。

**Comment by AnserBaby** [comment]
我也遇到了，更新到28，在安卓10，切换地图时奔溃
FORTIFY: pthread_mutex_destroy called on a destroyed mutex (0xba033fbc)
Fatal signal 6 (SIGABRT), code 0 (SI_USER) in tid 21503 (GLThread 9374), pid 21042 (gfuil.bmap.lite)
